const quotes = [
  "Success starts with showing up.",
  "Small progress is still progress.",
  "Discipline beats motivation.",
  "Dream big. Start small.",
  "Consistency creates results.",
  "Your future depends on today.",
  "Focus on improvement, not perfection.",
  "Action cures fear.",
  "Do it tired, do it anyway.",
  "Confidence comes from practice.",
  "Stay hungry for growth.",
  "Every expert was once a beginner.",
  "Push yourself daily.",
  "Difficult roads create strong people.",
  "Be stronger than your excuses.",
  "One step at a time.",
  "Hard work changes everything.",
  "Keep learning, keep growing.",
  "Winners never quit early.",
  "Make yourself proud.",
  "Success loves consistency.",
  "You become what you repeat.",
  "Progress over excuses.",
  "Work silently, shine loudly.",
  "Patience builds greatness.",
  "Learn from every mistake.",
  "Energy flows where focus goes.",
  "Start before you feel ready.",
  "Growth begins outside comfort zones.",
  "Your habits shape your future.",
  "Believe and build.",
  "Stay focused on your mission.",
  "Done is better than perfect.",
  "Fear disappears after action.",
  "Effort never goes to waste.",
  "Keep moving forward.",
  "Success takes repetition.",
  "Nothing changes without action.",
  "Motivation fades, discipline stays.",
  "One good day can change everything.",
  "Chase progress, not applause.",
  "Build skills, not excuses.",
  "Your mindset matters.",
  "Learn something every day.",
  "Strong minds create strong lives.",
  "Keep your standards high.",
  "The grind always pays back.",
  "Push beyond limits.",
  "Results require patience.",
  "Focus. Learn. Execute.",
  "You are capable of more.",
  "Great things take time.",
  "Work until it feels easy.",
  "Consistency beats intensity.",
  "Success is earned daily.",
  "Make discipline your lifestyle.",
  "Stay committed to the process.",
  "Growth is uncomfortable.",
  "Think less, start more.",
  "Your only competition is yesterday.",
  "Create more than you consume.",
  "Every day is a fresh start.",
  "Improve by one percent daily.",
  "The best project is self-improvement.",
  "Learning never stops.",
  "Stay curious and fearless.",
  "Failure teaches faster than success.",
  "Take risks intelligently.",
  "Ideas need execution.",
  "Build a life you respect.",
  "Hard choices build easy lives.",
  "Stay humble, work hard.",
  "Success begins with discipline.",
  "You miss every shot not taken.",
  "Time rewards consistency.",
  "Nothing worthwhile is instant.",
  "A focused mind is powerful.",
  "Your attitude shapes outcomes.",
  "Don’t stop at average.",
  "Keep building your future.",
  "Pressure creates diamonds.",
  "Success is a daily habit.",
  "Learn, apply, repeat.",
  "Greatness requires sacrifice.",
  "Stay patient with your journey.",
  "Every moment is a new chance.",
  "Be addicted to growth.",
  "Keep your vision clear.",
  "Hard work beats talent sometimes.",
  "Stay consistent even when unnoticed.",
  "The process creates champions.",
  "Discipline creates freedom.",
  "Start now, adjust later.",
  "You can always improve.",
  "Focus on becoming valuable.",
  "The comeback is always possible.",
  "Stay dedicated to your goals.",
  "Success is built quietly.",
  "Keep going no matter what.",
  "Your journey is unique."
];

// console.log(quotes.length)

const h1 = document.querySelector("h1")
const h4 = document.querySelector("h4")
const btn = document.querySelector("button")


function showQuote(e){
    const idx = Math.floor(Math.random()*100);
    h1.textContent = quotes[idx];
    h4.innerText = "Click Again for New Quote...!"

}

btn.addEventListener('click' , showQuote);