export const users = [
  {
    "id": 1,
    "firstName": "Arjun",
    "lastName": "Sharma",
    "email": "arjun.sharma@example.com",
    "phone": "+91-9876543210",
    "age": 24,
    "gender": "Male",
    "city": "Delhi",
    "state": "Delhi",
    "country": "India",
    "isActive": true
  },
  {
    "id": 2,
    "firstName": "Priya",
    "lastName": "Verma",
    "email": "priya.verma@example.com",
    "phone": "+91-9876543211",
    "age": 22,
    "gender": "Female",
    "city": "Mumbai",
    "state": "Maharashtra",
    "country": "India",
    "isActive": true
  },
  {
    "id": 3,
    "firstName": "Rahul",
    "lastName": "Singh",
    "email": "rahul.singh@example.com",
    "phone": "+91-9876543212",
    "age": 27,
    "gender": "Male",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "country": "India",
    "isActive": false
  },
  {
    "id": 4,
    "firstName": "Neha",
    "lastName": "Gupta",
    "email": "neha.gupta@example.com",
    "phone": "+91-9876543213",
    "age": 25,
    "gender": "Female",
    "city": "Jaipur",
    "state": "Rajasthan",
    "country": "India",
    "isActive": true
  },
  {
    "id": 5,
    "firstName": "Vikram",
    "lastName": "Patel",
    "email": "vikram.patel@example.com",
    "phone": "+91-9876543214",
    "age": 29,
    "gender": "Male",
    "city": "Ahmedabad",
    "state": "Gujarat",
    "country": "India",
    "isActive": true
  },
  {
    "id": 6,
    "firstName": "Ananya",
    "lastName": "Rao",
    "email": "ananya.rao@example.com",
    "phone": "+91-9876543215",
    "age": 23,
    "gender": "Female",
    "city": "Bengaluru",
    "state": "Karnataka",
    "country": "India",
    "isActive": true
  },
  {
    "id": 7,
    "firstName": "Karan",
    "lastName": "Mehta",
    "email": "karan.mehta@example.com",
    "phone": "+91-9876543216",
    "age": 31,
    "gender": "Male",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "country": "India",
    "isActive": false
  },
  {
    "id": 8,
    "firstName": "Sneha",
    "lastName": "Joshi",
    "email": "sneha.joshi@example.com",
    "phone": "+91-9876543217",
    "age": 26,
    "gender": "Female",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "isActive": true
  },
  {
    "id": 9,
    "firstName": "Rohan",
    "lastName": "Kapoor",
    "email": "rohan.kapoor@example.com",
    "phone": "+91-9876543218",
    "age": 28,
    "gender": "Male",
    "city": "Hyderabad",
    "state": "Telangana",
    "country": "India",
    "isActive": true
  },
  {
    "id": 10,
    "firstName": "Meera",
    "lastName": "Nair",
    "email": "meera.nair@example.com",
    "phone": "+91-9876543219",
    "age": 30,
    "gender": "Female",
    "city": "Kochi",
    "state": "Kerala",
    "country": "India",
    "isActive": false
  }
]